prefix : <http://purl.orthodb.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix : <http://purl.orthodb.org/>
select DISTINCT
(STRAFTER(xsd:string(?entId),"http://rdf.ebi.ac.uk/resource/ensembl/") as ?entId)
(STRAFTER(xsd:string(?orthoGroup),"http://purl.orthodb.org/odbgroup/") as ?orthoGroup)
(xsd:integer(?orthoDist) AS ?orthoDist) ?orthoSpecies
	(STRAFTER(xsd:string(?orthoDBId),"http://purl.orthodb.org/odbgene/") as ?orthoDBId)
?orthoHGNC ?orthoEntId ?orthoEnsembleGeneId


where {
?orthoDBId a :Gene;
      :name ?orthoHGNC ;
      :memberOf ?orthoGroup ;
      :description ?description;
      up:organism/a [ up:scientificName ?orthoSpecies ].
OPTIONAL {
      ?orthoDBId :xref [ :xrefResource [ a ?updb ;
                                    rdfs:label ?orthoEntId ] ] .
      FILTER (regex(?updb, "^.*Uniprot"))
}

OPTIONAL {
      ?orthoDBId :xref [ :xrefResource [ a ?endb ;
                                    rdfs:label ?orthoEnsembleGeneId ] ] .
      FILTER (regex(?endb, "^.*Ensembl"))
}

?orthoGroup a :OrthoGroup;
    :ogBuiltAt [ :taxTreeDistance ?orthoDist ] ;
    !:memberOf/:xref/:xrefResource ?entId .

FILTER (regex(?orthoSpecies, "^.*danio", "i") && regex(?orthoSpecies, "^.*rerio", "i" ))
#FILTER (regex(?orthoSpecies, "^.*{{gname}}", "i") && regex(?orthoSpecies, "^.*{{spname}}", "i" ))

#VALUES ?entId {uniprot:P60484}
VALUES ?entId {ensembl:ENSG00000171862}
#VALUES ?entId {{{upid}}}
}
ORDER BY ?orthoDist
