PREFIX wp:    <http://vocabularies.wikipathways.org/wp#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX bp: <http://www.biopax.org/release/biopax-level3.owl#>

SELECT DISTINCT ?entity ?member ?eRefNested ?mType ?mLocRef ?memberRef
FROM <http://www.ontotext.com/explicit>
WHERE
{
?entity bp:entityReference ?eRefNested .
# VALUES ?eRefNested {<http://pathwaycommons.org/pc11/#ProteinReference_bc9de4aeee0303b2a1f9851a6df6c8df>}

VALUES ?eRefNested {{{entity}}}

    ?entity bp:memberPhysicalEntity ?member .
    ?member a ?mType ;
            bp:xref ?memberRef ;
            bp:cellularLocation [ bp:term ?mLoc ;
                                  bp:xref ?mLocRef ] .
    ?memberRef a bp:UnificationXref
}
GROUP BY ?entity ?member ?eRefNested ?mType ?mLocRef ?memberRef
